[package]
name = "connect4_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
clap = { version = "4.0", features = ["derive"] }
console = "0.15.2"
rand = "0.8.5"
